// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package rest

import "strings"

type GetPostCommentsEndpoint struct{}

func (p GetPostCommentsEndpoint) Path(postId string) string {
	message := "/api/posts/{postId}/comments"
	message = strings.Replace(message, "{postId}", postId, -1)
	return message
}

type GetPostByIdEndpoint struct{}

func (p GetPostByIdEndpoint) Path(postId string) string {
	message := "/api/posts/{postId}"
	message = strings.Replace(message, "{postId}", postId, -1)
	return message
}

type GetPostsEndpoint struct{}

func (p GetPostsEndpoint) Path() string {
	message := "/api/posts"
	return message
}

type GetUserByIdEndpoint struct{}

func (p GetUserByIdEndpoint) Path(userId string) string {
	message := "/api/users/{userId}"
	message = strings.Replace(message, "{userId}", userId, -1)
	return message
}

type Paths struct {
	GetPostCommentsEndpoint GetPostCommentsEndpoint
	GetPostByIdEndpoint     GetPostByIdEndpoint
	GetPostsEndpoint        GetPostsEndpoint
	GetUserByIdEndpoint     GetUserByIdEndpoint
}
