// Code generated by github.com/manuelarte/gospecpaths. DO NOT EDIT.

package rest

import "strings"

type GetSessionEndpoint struct{}

func (p GetSessionEndpoint) Path() string {
	message := "/api/session"
	return message
}

type GetPostCommentsEndpoint struct{}

func (p GetPostCommentsEndpoint) Path(postId string) string {
	message := "/api/posts/{postId}/comments"
	message = strings.Replace(message, "{postId}", postId, -1)
	return message
}

type GetPostByIDEndpoint struct{}

func (p GetPostByIDEndpoint) Path(postId string) string {
	message := "/api/posts/{postId}"
	message = strings.Replace(message, "{postId}", postId, -1)
	return message
}

type GetPostsEndpoint struct{}

func (p GetPostsEndpoint) Path() string {
	message := "/api/posts"
	return message
}

type GetUserByIDEndpoint struct{}

func (p GetUserByIDEndpoint) Path(userId string) string {
	message := "/api/users/{userId}"
	message = strings.Replace(message, "{userId}", userId, -1)
	return message
}

type Paths struct {
	GetSessionEndpoint      GetSessionEndpoint
	GetPostCommentsEndpoint GetPostCommentsEndpoint
	GetPostByIDEndpoint     GetPostByIDEndpoint
	GetPostsEndpoint        GetPostsEndpoint
	GetUserByIDEndpoint     GetUserByIDEndpoint
}
