### Get intro blog

GET http://localhost:8080/blogs?name=intro.txt

### Get private info

GET http://localhost:8080/blogs?name=../internal/private.txt

### TODO: Get /etc/passwd

GET http://localhost:8080/static/blogs?name=...

### Get all blogs

GET http://localhost:8080/blogs
Content-Type: application/json

### Get one blog
GET http://localhost:8080/blogs/1/view
Content-Type: text/html

### Get Blog comments
GET http://localhost:8080/blogs/1/comments
Content-Type: application/json

### Create blog comments
POST http://localhost:8080/blogs/1/comments
Content-Type: application/json

{
  "blogId": 1,
  "userId": 2,
  "comment": "Very nice article"
}