### Get one Post
GET http://localhost:8080/posts/1/view
Content-Type: text/html

### Get Post comments
GET http://localhost:8080/api/posts/1/comments
Content-Type: application/json

### Scenario 1. Create Post Comment
POST http://localhost:8080/api/posts/1/comments
Content-Type: application/json

{
  "postID": 1,
  "userID": 2,
  "comment": "Very nice article"
}

### Scenario 1. Create Post comment for another user (e.g. admin user userId=1)
POST http://localhost:8080/api/posts/1/comments
Content-Type: application/json

{
  "postID": 1,
  "userID": 1,
  "comment": "Horrible article, you should delete it."
}

### Scenario 2. HTML injection
POST http://localhost:8080/api/posts/1/comments
Content-Type: application/json

{
  "postID": 1,
  "userID": 1,
  "comment": "Horrible article, you should delete it. <script type='text/javascript'>alert('Hello')</script>"
}
