### Get one Post
GET {{baseUrl}}/posts/1/view
Content-Type: text/html

### Get Post comments
GET {{baseUrl}}/api/posts/1/comments
Content-Type: application/json

### Scenario 1. Create Post Comment
POST {{baseUrl}}/api/posts/1/comments
Content-Type: application/json

{
  "postId": 1,
  "userId": 2,
  "comment": "Very nice article"
}

### Scenario 1. Create Post comment for another user (e.g. admin user userId=1)
POST {{baseUrl}}/api/posts/1/comments
Content-Type: application/json

{
  "postId": 1,
  "userId": 1,
  "comment": "Horrible article, you should delete it."
}

### Scenario 2. HTML injection
POST {{baseUrl}}/api/posts/1/comments
Content-Type: application/json

{
  "postId": 1,
  "userId": 1,
  "comment": "Horrible article, you should delete it. <script type='text/javascript'>alert('Hello')</script>"
}
