### HTTP Client example to use for '1. Login User - POST /users/login'

### 1. Scenario: normal login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "username": "gowasp",
  "password": "gowasp"
}

##### 2. Scenario: logout
### 2.1 Logout
DELETE {{baseUrl}}/users/logout

### 2.2 Try to log in without knowing any credentials
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "username": "....",
  "password": "...."
}
