### HTTP Client example to use for '1. Login User - POST /users/login'

### 1. Scenario: normal login
POST http://localhost:8080/users/login
Content-Type: application/x-www-form-urlencoded

email=gowasp@test.com&password=gowasp

##### 2. Scenario: logout
### 2.1 Logout
DELETE http://localhost:8080/users/logout

### 2.2 Try to log in without knowing any credentials
POST http://localhost:8080/users/login
Content-Type: application/x-www-form-urlencoded

email=...&password=...